'use client';

import { AnimatePresence, LayoutGroup, motion } from 'motion/react';
import { ArrowUpRight, Code2, ExternalLink, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { projects } from '@/data/portfolio';
import type { Project, ProjectCategory } from '@/types/portfolio';
import { AnimatedSection, smoothSpring } from '@/components/ui/AnimatedSection';

const filters = ['All', 'Cloud & Infrastructure', 'Distributed Systems', 'Machine Learning', 'Full Stack'] as const;

function ProjectModal({ project, close }: { project: Project; close: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { closeRef.current?.focus(); const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; const escape = (e: KeyboardEvent) => e.key === 'Escape' && close(); document.addEventListener('keydown', escape); return () => { document.body.style.overflow = previous; document.removeEventListener('keydown', escape); }; }, [close]);
  return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(e) => e.target === e.currentTarget && close()}><motion.div role="dialog" aria-modal="true" aria-labelledby="project-modal-title" className="project-modal" initial={{ opacity: 0, y: 24, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 18, scale: 0.98 }} transition={smoothSpring}><button className="icon-button modal-close" ref={closeRef} onClick={close} aria-label="Close project details"><X /></button><p className="section-kicker">{project.category}</p><h2 id="project-modal-title">{project.title}</h2><p className="modal-summary">{project.summary}</p><div className="modal-columns"><div><p className="modal-label">The problem</p><p>{project.challenge}</p></div><div><p className="modal-label">The approach</p><p>{project.approach}</p></div></div><div className="modal-detail"><p className="modal-label">Key contributions & decisions</p><ul>{project.details.map((detail) => <li key={detail}>{detail}</li>)}</ul></div><div className="tag-row">{project.technologies.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div><div className="modal-links"><a href={project.github}><Code2 size={16} /> GitHub <ArrowUpRight size={14} /></a><a href={project.demo}><ExternalLink size={16} /> Live demo <ArrowUpRight size={14} /></a></div></motion.div></motion.div>;
}

export function ProjectsSection() { const [filter, setFilter] = useState<typeof filters[number]>('All'); const [selected, setSelected] = useState<Project | null>(null); const shown = filter === 'All' ? projects : projects.filter((project) => project.category === filter as ProjectCategory); return <section id="projects" className="section-wrap section-tint"><AnimatedSection><p className="section-kicker">03 / Selected projects</p><div className="section-intro project-intro"><div><h2>From reliable systems to intelligent products.</h2><p>Selected work across cloud infrastructure, distributed computing, machine learning, computer vision, and full-stack product delivery.</p></div><span className="project-count">{String(shown.length).padStart(2, '0')} projects</span></div></AnimatedSection><div className="filter-row" role="tablist" aria-label="Filter projects">{filters.map((item) => <button key={item} role="tab" aria-selected={filter === item} className={filter === item ? 'filter active' : 'filter'} onClick={() => setFilter(item)}>{item}</button>)}</div><LayoutGroup><motion.div className="project-grid" layout>{shown.map((project) => <motion.article key={project.id} layoutId={project.id} layout className="project-card" tabIndex={0} onClick={() => setSelected(project)} onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && setSelected(project)} whileHover={{ y: -6 }} whileFocus={{ y: -4 }} transition={smoothSpring}><div className="project-visual"><span className="visual-index">{project.id === 'observability' ? 'OBS / 01' : project.id.toUpperCase().slice(0, 8)}</span><div className="visual-scan" /><ArrowUpRight className="card-arrow" size={19} /></div><div className="project-card-body"><p className="eyebrow">{project.category}</p><h3>{project.title}</h3><p>{project.summary}</p><div className="project-footer"><div className="tag-row">{project.technologies.slice(0, 3).map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div>{project.metric && <span className="project-metric">{project.metric}</span>}</div></div></motion.article>)}</motion.div></LayoutGroup><AnimatePresence>{selected && <ProjectModal project={selected} close={() => setSelected(null)} />}</AnimatePresence></section>; }
